### ISSUE TITLE
Widget crashed: ALSAWidget (click to hide)

### ISSUE THREAD

**Issue by Arsh90** [elParaguayo/qtile-extras#13] opened 2021-12-06 08:00 UTC
![06-12-2021 13:28:56](https://user-images.githubusercontent.com/87270576/144808977-45cf4734-bd48-448b-b82e-d640d9075bea.png)

**Comment by elParaguayo** [comment] 2021-12-06 09:14
Duplicate of #12

**Closed by elParaguayo** 2021-12-06 09:14 UTC
