### ISSUE TITLE
Issues after Visualiser update

### ISSUE THREAD

**Issue by gibranlp** [elParaguayo/qtile-extras#301] opened 2023-11-16 00:36 UTC
Hey man,

Im still having issues with the Upower and the Mpris i get the "No metadata for current track" message for everything.

I have Qtile 0.23.1.dev79+g5203110b

I get this erron on the log

`Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/qtile_extras/widget/upower.py", line 149, in _config_async
    await self._setup_dbus()
  File "/usr/lib/python3.11/site-packages/qtile_extras/widget/upower.py", line 168, in _setup_dbus
    self.configured = await self._update_battery_info()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qtile_extras/widget/upower.py", line 282, in _update_battery_info
    if ttf == 0 and battery["flags"] != BatteryState.FULL:
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/hook.py", line 178, in fire
    for i in subscriptions[self.name].get(event, []):
             ~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'qtile-extras'

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/qtile_extras/widget/upower.py", line 282, in _update_battery_info
    if ttf == 0 and battery["flags"] != BatteryState.FULL:
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/libqtile/hook.py", line 178, in fire
    for i in subscriptions[self.name].get(event, []):
             ~~~~~~~~~~~~~^^^^^^^^^^^

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/widget/mpris2widget.py", line 262, in process_message
    self.parse_message(*message.body)
  File "/usr/lib/python3.11/site-packages/qtile_extras/widget/mpris2widget.py", line 142, in parse_message
    hook.fire("mpris_status_change", changed_properties["PlaybackStatus"].value)
  File "/usr/lib/python3.11/site-packages/libqtile/hook.py", line 178, in fire
    for i in subscriptions[self.name].get(event, []):
             ~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'qtile-extras'
2023-11-15 18:28:03,193 ERROR libqtile loop.py:_handle_exception():L62 Exception in event loop:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/libqtile/widget/mpris2widget.py", line 262, in process_message
    self.parse_message(*message.body)
  File "/usr/lib/python3.11/site-packages/qtile_extras/widget/mpris2widget.py", line 142, in parse_message
    hook.fire("mpris_status_change", changed_properties["PlaybackStatus"].value)
  File "/usr/lib/python3.11/site-packages/libqtile/hook.py", line 178, in fire
    for i in subscriptions[self.name].get(event, []):
             ~~~~~~~~~~~~~^^^^^^^^^^^`

Mpris
![area_screenshot_3](https://github.com/elParaguayo/qtile-extras/assets/2806964/78a072f2-b3a3-4599-8517-70a76aed9501)

Upower
This one is weird when i open the the Upower shows the date again
![area_screenshot_4](https://github.com/elParaguayo/qtile-extras/assets/2806964/fa5bf712-9d67-4bb8-8fc2-cc70caa9affe)

**Comment by elParaguayo** [comment] 2023-11-16 05:23
OK - so this does seem to be related to the hooks not working for you. Can you run `qtile cmd-obj -o cmd -f eval -a hook.subscriptions` and paste the output here.

**Comment by elParaguayo** [comment] 2023-11-16 15:02
Bizarre. I can see the `qtile-extras` key there! What do you get if you do `qtile cmd-obj -o cmd -f eval -a hook.subscriptions['qtile-extras']`.

Separately, that's a _lot_ of hooks caused by the groupbox widget. Feels like something's gone wrong there unless you've got loads of groupboxes!

**Comment by gibranlp** [comment] 2023-11-16 17:09
All i get is from qtile cmd-obj -o cmd -f eval -a hook.subscriptions['qtile-extras']

`zsh: no matches found: hook.subscriptions[qtile-extras]`

I must comment this is the fresh install i was talking about so everthing is new.

And yeah I'm testing a multicolor groups in the bar, for now i have just created 10 different groupboxes so that's on me. xD

**Comment by elParaguayo** [comment] 2023-11-16 17:15
That's just your shell not parsing the command correctly. Try `cmd-obj -o cmd -f eval -a "hook.subscriptions['qtile-extras']"`

As for your second question, do you mean different background per group? If so, no, not possible with the current widget.

**Comment by gibranlp** [comment] 2023-11-16 17:18
I get 

`(False, "KeyError: 'qtile-extras'")`

**Comment by elParaguayo** [comment] 2023-11-16 17:22
What!? It was listed in your previous post. There's something very weird thing going on (the hooks work for me) or I'm missing something obvious.

**Comment by gibranlp** [comment] 2023-11-16 17:27
This is with just one groupbox 


`~
 qtile cmd-obj -o cmd -f eval -a hook.subscriptions
(True,
 "{'qtile': {'setgroup': [<function move_sticky_windows at 0x7fc7e5024900>, "
 '<bound method _GroupBase._hook_response of '
 '<libqtile.widget.groupbox.GroupBox object at 0x7fc7e6567150>>, <bound method '
 'Bar.set_layer of <libqtile.bar.Bar object at 0x7fc7e65852d0>>, <bound method '
 'Qtile.update_desktops of <libqtile.core.manager.Qtile object at '
 "0x7fc7e8ccba50>>], 'client_killed': [<function remove_sticky_windows at "
 '0x7fc7e5025ee0>, <bound method DGroups._del of <libqtile.dgroups.DGroups '
 'object at 0x7fc7e6524cd0>>, <bound method _GroupBase._hook_response of '
 '<libqtile.widget.groupbox.GroupBox object at 0x7fc7e6567150>>, <bound method '
 "ScratchPad.on_client_killed of <group.Group ('scratchpad')>>], 'startup': "
 "[<function start at 0x7fc7e50254e0>], 'startup_once': [<function start_once "
 "at 0x7fc7e5024c20>], 'client_new': [<function follow_window at "
 '0x7fc7e5025a80>, <bound method DGroups._add of <libqtile.dgroups.DGroups '
 "object at 0x7fc7e6524cd0>>], 'client_name_updated': [<function "
 'follow_window_name at 0x7fc7e5027c40>, <bound method '
 'WindowName.hook_response of <libqtile.widget.windowname.WindowName object at '
 "0x7fc7e6567ed0>>], 'addgroup': [<bound method DGroups._addgroup of "
 "<libqtile.dgroups.DGroups object at 0x7fc7e6524cd0>>], 'client_managed': "
 '[<bound method _GroupBase._hook_response of '
 '<libqtile.widget.groupbox.GroupBox object at 0x7fc7e6567150>>], '
 "'client_urgent_hint_changed': [<bound method _GroupBase._hook_response of "
 '<libqtile.widget.groupbox.GroupBox object at 0x7fc7e6567150>>], '
 "'group_window_add': [<bound method _GroupBase._hook_response of "
 '<libqtile.widget.groupbox.GroupBox object at 0x7fc7e6567150>>], '
 "'current_screen_change': [<bound method _GroupBase._hook_response of "
 '<libqtile.widget.groupbox.GroupBox object at 0x7fc7e6567150>>, <bound method '
 'WindowName.hook_response_current_screen of '
 '<libqtile.widget.windowname.WindowName object at 0x7fc7e6567ed0>>], '
 "'changegroup': [<bound method _GroupBase._hook_response of "
 '<libqtile.widget.groupbox.GroupBox object at 0x7fc7e6567150>>], '
 "'focus_change': [<bound method WindowName.hook_response of "
 '<libqtile.widget.windowname.WindowName object at 0x7fc7e6567ed0>>], '
 "'float_change': [<bound method WindowName.hook_response of "
 '<libqtile.widget.windowname.WindowName object at 0x7fc7e6567ed0>>, <bound '
 "method ScratchPad.on_float_change of <group.Group ('scratchpad')>>], "
 "'client_focus': [<function Prompt._configure.<locals>.f at 0x7fc7e7b28ea0>], "
 "'startup_complete': [<bound method Bar.set_layer of <libqtile.bar.Bar object "
 "at 0x7fc7e65852d0>>], 'screen_change': [<bound method "
 'Qtile.reconfigure_screens of <libqtile.core.manager.Qtile object at '
 '0x7fc7e8ccba50>>]}}')

~
 qtile cmd-obj -o cmd -f eval -a "hook.subscriptions['qtile-extras']"
(False, "KeyError: 'qtile-extras'")`

**Comment by elParaguayo** [comment] 2023-11-16 17:45
Yes. Key is definitely missing that time. Are you restarting qtile or reloading the config? It shouldn't make a difference but it's an idea.

**Comment by gibranlp** [comment] 2023-11-16 17:46
Yeah, i reload the config continously

**Comment by elParaguayo** [comment] 2023-11-16 17:47
Ok. Let me see if I can recreate. 

Can you restart qtile and see if the key is there?

**Comment by gibranlp** [comment] 2023-11-16 17:52
When i restart Qtile it works, but if i reload the config it doesn't work again

**Comment by elParaguayo** [comment] 2023-11-16 18:01
Great. So we've found the bug. Now to find a solution.

**Comment by elParaguayo** [comment] 2023-11-16 18:06
OK - I've found the problem. Will work on a fix which will need to be pushed to qtile rather than qtile-extras.

**Comment by gibranlp** [comment] 2023-11-16 18:22
Awesome, thanks man

**Comment by elParaguayo** [comment] 2023-11-16 18:27
If possible, can you test https://github.com/qtile/qtile/pull/4579

**Comment by gibranlp** [comment] 2023-11-17 14:47
It works now! awesome, thanks man!

**Comment by elParaguayo** [comment] 2023-11-17 15:11
Nice. Thanks for confirming. I'll get someone to review the PR in qtile so we can get it merged.

**Closed** 2023-12-15 17:49 UTC
